export const SEQUELIZE = 'SEQUELIZE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const FOLDER_REPOSITORY = 'FOLDER_REPOSITORY';
export const FILE_REPOSITORY = 'FILE_REPOSITORY';
export const PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';
export const LINK_CODE_REPOSITORY = 'LINK_CODE_REPOSITORY';
