version: '3.0'

services:
  backend:
    container_name: test_file
    build:
      context: ./
    env_file:
      - ./.env
    volumes:
      - ./test_file:/test_file
      - /node_modules
    ports:
      - 3000:3000
    depends_on:
      - mysql_tmp
      - redis_tmp
    restart: always
    networks:
      - my_network

  mysql_tmp:
    container_name: mysql_tmp
    image: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  redis_tmp:
    container_name: redis_tmp
    image: redis
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
